packages:
  - "apps/*"
  - "packages/*"
  - "plugins/*"
allowBuilds:
  '@google/genai': true
  '@serialport/bindings-cpp': true
  electron: true
  esbuild: true
  protobufjs: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@google/genai@2.16.0'
